spring:
  application:
    name: "@project.artifactId@"
  thymeleaf:
    enabled: false # Discovery Server Dashboard uses FreeMarker -> Disable Thymeleaf
  boot:
    admin:
      client:
        enabled: false # Set at 'true' for Spring Boot Admin self-supervision

server:
    port: 8761

eureka:
  dashboard:
    path: /eureka-dashboard # Path to the Eureka Dashboard ('/' is for Spring Boot Admin Dashboard)
  instance:
      appname: ${spring.application.name}
      instanceId: ${spring.application.name}:${random.value}
  client:
      fetchRegistry: true # Important : Required at 'true' for Spring Boot Admin server good working
      registerWithEureka: false # Set at 'true' for Spring Boot Admin self-supervision
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
  server:
      waitTimeInMsWhenSyncEmpty: 0
      enable-self-preservation: false
        
## With Spring Actuator, theses data will be visible from '/info'        
info:
  name: "@project.artifactId@"
  version: "@project.version@"
  description: "@project.description@"
  running-profile: ${spring.profiles.active}